name: Update recent activity

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jamesgeorge007/github-activity-readme@master
        with:
          COMMIT_MSG: "chore: update recent activity"
          MAX_LINES: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
