name: Update recent activity

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Readme-Workflows/recent-activity@v2.4.1
        with:
          GH_USERNAME: sachith89
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
